SET client_encoding TO 'UTF8';
BEGIN;

DROP TABLE IF EXISTS "role", "user","animal","request"; 

CREATE TABLE "role" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL
);

CREATE TABLE "user" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(100) NOT NULL,
    "firstname" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password"VARCHAR(255) NOT NULL,
    "role_id" INT NOT NULL REFERENCES "role"("id") ON DELETE CASCADE
);

CREATE TABLE "animal" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "species" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "race" VARCHAR(100),
  "gender" VARCHAR(25),
  "location" VARCHAR(255),
  "photo" TEXT,
  "birthday" DATE,
  "availability" BOOLEAN NOT NULL,
  "user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE
);

CREATE TABLE "request" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "date" DATE NOT NULL,
    "status" VARCHAR(25) NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "animal_id" INT NOT NULL REFERENCES "animal"("id") ON DELETE CASCADE
);



COMMIT;